# Generated by Django 2.1.5 on 2019-01-14 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess', models.IntegerField(help_text='The submitted answer')),
            ],
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Name of test', max_length=80, unique=True)),
                ('description', models.TextField(default='', help_text='Description of the test (shown on listing).')),
                ('number_of_problems', models.IntegerField(default=0, help_text='Number of problems in the test')),
                ('exam_window_start', models.DateTimeField(help_text='Start of test window')),
                ('exam_window_end', models.DateTimeField(help_text='End of test window')),
                ('live_scoring', models.BooleanField(default=False, help_text='Does the test use live scoring?')),
                ('active', models.BooleanField(default=False, help_text='Is the contest currently active?')),
                ('max_attempts', models.PositiveIntegerField(default=1, help_text='Number of available attempts on each problem on the test')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='The problem number on the test')),
                ('answer', models.IntegerField(help_text='The answer to the problem')),
                ('weight', models.IntegerField(default=1, help_text='The weight of the problem')),
                ('test', models.ForeignKey(help_text='The test that the problem is on', on_delete=django.db.models.deletion.CASCADE, to='onlinemathopen.Contest')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='The time the submission was made')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', help_text='Name of team', max_length=80)),
                ('real_names', models.CharField(help_text='Comma separated list of the real student(s) taking the test.', max_length=320)),
                ('leader', models.ForeignKey(help_text='The user that registered the team', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(help_text='The test that the team is for', on_delete=django.db.models.deletion.CASCADE, to='onlinemathopen.Contest')),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='team',
            field=models.ForeignKey(help_text='The team that made the submission', on_delete=django.db.models.deletion.CASCADE, to='onlinemathopen.Team'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='problem',
            field=models.ForeignKey(help_text='The problem that is being attempted', on_delete=django.db.models.deletion.CASCADE, to='onlinemathopen.Problem'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='submission',
            field=models.ForeignKey(help_text='The submission that this answer attempt belongs to', on_delete=django.db.models.deletion.CASCADE, to='onlinemathopen.Submission'),
        ),
    ]
