# Generated by Django 2.1.5 on 2019-02-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinemathopen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='max_attempts',
            field=models.PositiveIntegerField(help_text='Number of available attempts on each problem on the test (ignore if live scoring is off)'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='number_of_problems',
            field=models.IntegerField(default=30, help_text='Number of problems in the test'),
        ),
    ]
