# Generated by Django 2.1.5 on 2019-02-09 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinemathopen', '0002_auto_20190201_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_answer', models.IntegerField(help_text='The current answer')),
                ('guesses_left', models.IntegerField(help_text='The number of guesses left (-1 means infinite)')),
                ('problem', models.ForeignKey(help_text='The problem that this status is linked to', on_delete=django.db.models.deletion.CASCADE, to='onlinemathopen.Problem')),
                ('team', models.ForeignKey(help_text='The team that this status is linked to', on_delete=django.db.models.deletion.CASCADE, to='onlinemathopen.Team')),
            ],
        ),
    ]
