# Generated by Django 2.2.4 on 2019-08-07 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinemathopen', '0003_problemstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='live_scoring',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='max_attempts',
        ),
        migrations.RemoveField(
            model_name='problemstatus',
            name='guesses_left',
        ),
    ]
