# Generated by Django 2.2.4 on 2019-08-08 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinemathopen', '0004_auto_20190807_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='leader',
            new_name='captain',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='weight',
        ),
    ]
