# Generated by Django 2.2.4 on 2019-08-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinemathopen', '0005_auto_20190808_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(help_text='Name of team', max_length=80),
        ),
    ]
