# Generated by Django 2.2.4 on 2019-08-29 03:24

from django.db import migrations, models
import django.db.models.deletion
import onlinemathopen.models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinemathopen', '0006_auto_20190809_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the file', max_length=80)),
                ('pdf_file', models.FileField(blank=True, help_text='The PDF file', null=True, upload_to=onlinemathopen.models.getFilePath)),
                ('test', models.ForeignKey(help_text='The test associated to the file', on_delete=django.db.models.deletion.CASCADE, to='onlinemathopen.Contest')),
            ],
        ),
    ]
